### ISSUE TITLE
Appendix after references?

### ISSUE THREAD

**Issue by dragonattheend** [resulumit/rmd_workshop#24]
Thanks a lot for the slides, really helpful!
How can I add appendix after references section? 

And a smaller question:
my knitted output doesn't center the quote after the abstract like in the `reproduce_this.pdf` file 
![image](https://user-images.githubusercontent.com/83570780/172474226-7b302af6-816d-469a-bf74-0124eed514e4.png)

**Comment by resulumit** [comment]
This space is for issues about the workshop, and not questions about rmarkdown. Still, let me answer the questions.

There is a slide about placing the list of references wherever you want, currently at: https://resulumit.com/teaching/rmd_workshop.html#230. If you googled "appendix after references rmarkdown", the first link would provide you with the same answer --- only quicker.

The second question refers to a block quote (currently covered at: https://resulumit.com/teaching/rmd_workshop.html#93), which is different than centring the text. The block quote in your output looks as it should.
